;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        better-beginning-of-line
        python-indent-dedent-line-backspace
        ))

(setq mc/cmds-to-run-once
      '(
        ))
